docker-compose-it2/docker-compose.yml
Added support for Event resource, also I have moved the images from dataclay dockerhub to mf2c docker hub in order to have consistent versions of dcproxy and dataclay (2.6 now).
=> Adding versioning to dataclay images

docker-compose-it2/analytics_engine.conf, docker-compose-it2/docker-compose.yml, docker-compose-it2/landscaper.cfg
I have been testing analytics, snap, etc, with @svoorakk , and found that the connections between them were wrong. 
I prefer to set then `hostname` in the docker-compose.yml, instead of assuming the name is mf2c_xxx_1 (which happens when running `docker-compose -p mf2c`).  WDYT?
=> Fix connections between intel components

docker-compose-it2/landscaper.cfg
Modifying landscaper.cfg and a listener to default configuration so that the container will not exit. NOTE: In practice, the configuration (landscaper.cfg) is needed to be correctly edited based on the host requirements before starting the landscaper & landscaper web containers.
Output of hello-world.sh : 
iolie@IRILD039:~/mf2c/mf2c/docker-compose-it2$ sh ./hello-world.sh 
./hello-world.sh: 3: ./hello-world.sh: [[: not found
-e 
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   322  100    90  100   232    231    597 --:--:-- --:--:-- --:--:--   832
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total …
=> Modifying landscaper.cfg and a listener to default configuration

docker-compose-it2/docker-compose.yml, docker-compose-it2/landscaper.cfg
Usage of Snaptemp has been removed and replace with telem_start which is a smaller, alpine based image. The telem_start image also removes hardcoding of hostname in the telemetry task configuration.
Output of hello-world.sh
iolie@IRILD039:~/mf2c/mf2c/docker-compose-it2$ ./hello-world.sh
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   328  100    96  100   232   2526   6105 --:--:-- --:--:-- --:--:--  8631
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   283  100   156  100   127   4105   3342 --:--:-- --:--:-- --:--:--  7447
% Total    % Received % Xferd  Average …
=> Removing snaptemp and replacing with a smaller image (telem_start)

docker-compose-it2/docker-compose.yml
New version of mf2c/landscaper image, added new volume mappings to landscaper & web services.
Output of hello-world.sh
iolie@IRILD039:~/mf2c/mf2c/docker-compose-it2$ ./hello-world.sh 
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   684  100   166  100   518   2128   6641 --:--:-- --:--:-- --:--:--  8769
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   359  100   156  100   203    368    479 --:--:-- --:--:-- --:--:--   848
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  1325  100  1257 …
=> Changes to add endpoint for fetching landscaper log to landscaper web api

docker-compose/docker-compose.yml
Make landscaper logs be written to the same folder as docker-compose.
I'd question why this is even necessary, as docker already has a logging mechanism.
=> Don't pollute the user's home folder

docker-compose/docker-compose.yml
This is the same VPN server as before but has its key management re-engineered to be fully automated (no manual config required): it now generates fresh diffie helman keys (DH) and calls out to the infrastructure (trust) CA for server cert/keys, so deploys entirely out of the docker-compose file.
Note that the client code is only in mF2C/vpn; it has not yet been integrated into the agent - so deploying a standalone server is harmless.
I have tested deployment locally and it works. There is no open issue for this.
=> Added updated vpn server image to (fog) compose file

docker-compose/docker-compose.yml
with Service replicated in leaders + deletes + migration of objects caused by updates of agent leaders, backups and children + aware of update of agent ips + associated to new dataclaypre-relase 2.0.dev9
=> New dataClay 2.21

docker-compose/docker-compose.yml
Update analytics-engine to 0.5.5 to handle the error when an empty graph returned from the landscape.
=> Update analytics-engine to 0.5.5 to handle error when empty graph return

docker-compose/docker-compose.yml
This PR adds several improvements to SLA schema and functionality; it allows assessment of service availabilities relying on ServiceContainerMetrics written by analytics.
It also fix the errors to launch the docker-compose:
- no within quotes (without them, the YAML spec considers `no` as a boolean value, not a string)
- removes dependency of vpnclient to vpnserver (vpnserver does not exist); this may be not intended, but at least, it starts.
CHANGELOG: 
* Add current example of availability and usage [Román SG]
* Add integration test for new CIMI adapter [Román SG]
* Support availability in SLAs [Román SG]
* Add scope, schedule; and refactor assessment model [Román SG]
* Add Assessment.LastValues to agreement model [Román SG]
* Add generic adapter and most of the tests [Román SG]
* Add …
=> Bump up sla to 0.8; fix docker-compose file errors

docker-compose/docker-compose.yml
=> Fix the internal host name used for bootstrapping.

docker-compose/docker-compose.yml
when deploying the compose, the following error raised.
ERROR: yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
in "./docker-compose.yml", line 201, column 1
This bugfix replaces the \t character by whitespaces
=> Remove \t character from docker-compose

docker-compose/docker-compose.yml, docs/cau_client.md
I have aligned cau-client and cau (not in docker-compose) to accept only 2 params (deviceID, detectedLID) for getting an agent certificate.  (Also see https://github.com/mF2C/ResourceManagement/issues/35)  IDKey is not validated by Identification block.   There is only 1 change to the docker-compose file: bumped from cau-client version from 2.0 to 2.1.
=> Updated cau-client version to 2.1, no idkey param

docker-compose/docker-compose.yml
```
$ docker-compose -p mf2c ps slalite
Name                  Command                State              Ports       
---------------------------------------------------------------------------------
mf2c_slalite_1   /opt/slalite/run_slalite.sh   Up (healthy)   46030/tcp, 8090/tcp
```
=> Add SLA Mgmt health check in docker-compose

docker-compose/tests/identification-FullAgent.sh, docker-compose/tests/identification-Isolated.sh
The identification-Isolated.sh script tests the identification module even when it isnt running. It requieres privilegies to run docker commands and at the end of the testing, the container is stopped.
On the other hand, the identification-FullAgent.sh script assumes that the full agent is in execution, including of course, the identification module.
=> update the identification integration test

docker-compose/docker-compose.yml
actual inter-agent communication might not be ready to go through traefik (agent resource must be properly updated to specify which port to use, currently hardcoded to 1034 and discovery only provides the ip) - to talk
=> Exposing port until Discovery adapt to traefik ips

docker-compose/tests/aclib.sh
Replaced the hardcoded recipient's deviceid in the jwe request. 
`[root@stfc-tests tests]# ./aclib.sh
Tester needs privilege to run Docker commands...
Tests will be aborted if Agent does not have the necessary mF2C cedentials...
[ACLibTests]     Starting...
Extracting container id ....
Checking if agent credentials exist....
Setting ACLib IP...
network id: mf2c_default
ALib host ip set to 192.168.176.23
[ACLibTests]     SUCCESS: Got JWT from ACLib
[ACLibTests]     SUCCESS:  [CIMI] cloud-entry-point exists
[ACLibTests]     SUCCESS:  [CIMI] successfully pushed new session template for JWT tokens
[ACLibTests]     SUCCESS:  [CIMI] successful login with JWT token
[ACLibTests]     SUCCESS:  [CIMI] deleted JWT session template
[ACLibTests]     SUCCESS: JWT verified by ACLib
The payload: a top …
=> amended aclib.sh to remove hardcoded receipient did

docker-compose/docker-compose.yml
Added:
- Health check for Intel components: landscaper, neo4j, analytics, influxdb
=> Health check for Intel components #270

agent/docker-compose.yml, agent/docs/dcproxy.md, agent/docs/ds1java1.md, agent/docs/logicmodule1.md
Please move following docker images from mf2c/trunk before accepting: 
mf2c/trunk:dataclay-proxy-2.28
mf2c/trunk:dataclay-logicmodule-2.28
mf2c/trunk:dataclay-dsjava-2.28
To
mf2c/dataclay-proxy:2.28
mf2c/dataclay-logicmodule:2.28
mf2c/dataclay-dsjava:2.28
=> New dataclay 2.28 without controlling if node is reachable

microagent/docker-compose.yml, microagent/mf2c-entrypoint.sh
@cjdcordeiro the new ARM docker image for Res-Cat is `resCatlatest-V2.0.28-arm` which is in the `mf2c\trunk` repo and also I have modified the docker-image tag for microagent. Now the new version is - `1.0.5`. So, before you accept the PR, please build the microagent image with the new res-cat arm image and then accept it. I'd also like to inform you that @ALEJANDROJ19 has been already reviewed my code.
=> Fixed the storing point for the microagent's resource info

agent/docker-compose.yml, agent/docs/dcproxy.md, agent/docs/ds1java1.md, agent/docs/logicmodule1.md
Please move following docker images from mf2c/trunk before accepting: 
mf2c/trunk:dataclay-proxy-2.29
mf2c/trunk:dataclay-logicmodule-2.29
mf2c/trunk:dataclay-dsjava-2.29
To
mf2c/dataclay-proxy:2.29
mf2c/dataclay-logicmodule:2.29
mf2c/dataclay-dsjava:2.29
=> New dataClay 2.29 with resource control during updates

agent/docker-compose.yml, agent/docs/resource-bootstrap.md
Fix temporary files being included in the Docker image.
`.dockerignore` dooesn't work the same way as `.gitignore`. Who'da thunk it.
=> Upgrade resource-bootstrap to 2.8.6.

agent/docker-compose.yml
The lm-um healthcheck is failing because `wget` isn't available in the container. Other functionality is fine, and I have tested my workflow of deploying a swarm stack through mF2C. This may or may not be a deal breaker.
=> Update image versions for Swarm stack support.

agent/docker-compose.yml, agent/docs/resource-categorization.md, microagent/mf2c-entrypoint.sh
Modified the docker-compose file and mf2centrypoint.sh with the newly updated Res-Cat version for removing the `unavailable` agent IPs from the agent resource.
=> Updated the res-cat with new docker images

agent/docker-compose.yml, agent/docs/discovery.md, agent/mf2c.sh
- This PR corresponds to discovery version `mf2c/discovery:1.7` , where the GET IP method provided by discovery gets the interface name from the ENV variable (the one that is already set in `mf2c.sh` ) instead of using the first WLAN interface found, which may be different from the one used in `mf2c.sh` **only if the agent machine has more than 1 WLAN interface** . As a result, an `environment`  section has been added to the discovery part in docker-compose.
- Some obsolete commands have been also removed from `mf2c.sh`.
=> Discovery iface env
