mF2C/mF2C

docker-compose-it2/docker-compose.yml

Merged from master before PR (forgot sorry), hello-world script is returning 201

Dcproxy update

---

docker-compose-it2/docker-compose.yml
docker-compose-it2/landscaper.cfg

Output of hello-world.sh executed after docker compose file changes.
iolie@IRILD039:~/mf2c/docker-compose-it2$ ./hello-world.sh
{
"status" : 201,
"message" : "device/072975cb-df46-4a88-a763-4182f8367e08 created",
"resource-id" : "device/072975cb-df46-4a88-a763-4182f8367e08"
}{
"status" : 201,
"message" : "user/carpio created",
"resource-id" : "user/carpio"
}{
"status" : 201,
"message" : "service/c72c3d17-01f3-4235-b158-86ce24a64464 created",
"resource-id" : "service/c72c3d17-01f3-4235-b158-86ce24a64464"
}{
"status" : 201,
"message" : "agreement/cb414ad1-e51f-47d7-8229-69041a79bb08 created",
"resource-id" : "agreement/cb414ad1-e51f-47d7-8229-69041a79bb08"
}

Updating Landscaper & Analytics Engine Image versions

---

docker-compose-it2/docker-compose.yml

added cimi check
leader reelection
new leader backup protocol
Tests:

policies 2.0.0

---

docker-compose-it2/analytics_engine.conf
docker-compose-it2/docker-compose.yml
docker-compose-it2/landscaper.cfg

Changed the res-cat version from `latest-V2.0.8` to `latest-V2.0.9`

Changed the res-cat docker-image version

---

docker-compose-it2/docker-compose.yml
docker-compose-it2/landscaper.cfg

Integrating landscaper changes for device-dynamic resource updates. Also removing use of landscaper-api image, replacing it with landscaper image.

Device dynamic

---

docker-compose-it2/docker-compose.yml
docs/analytics_engine.md

Changing Analytics Engine version to 0.3.5 and modifying service name to analytics-engine

AE nan bug fix

---

docker-compose-it2/docker-compose.yml
docs/analytics_engine.md

Updating analytics-engine docker image to 0.4.0 which includes changes to optimize telemetry queries used to calculate utilization
Output of hello-world.sh
iolie@IRILD039:~/mf2c/mf2c/docker-compose-it2$ ./hello-world.sh 
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   684  100   166  100   518   2273   7095 --:--:-- --:--:-- --:--:--  9369
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   359  100   156  100   203    305    397 --:--:-- --:--:-- --:--:--   701
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent …

Optimal optimize

---

docker-compose-it2/docker-compose.yml
docs/policies.md

+ Added agent resource population
+ Added leaderIP
+ Documentation updated
+ Branch up to date

Policies patch

---

docker-compose/docker-compose.yml
docker-compose/landscaper.cfg
docs/analytics_engine.md
docs/landscaper.md

Landscaper version 0.6.5
Analytics Engine version 0.4.5
output of hello-world.sh 
iolie@IRILD039:~/tmp/mF2C/docker-compose$ ./hello-world.sh 
[HelloWorldTests]  Starting...
[HelloWorldTests]  SUCCESS: device dynamic "device-dynamic/4238c23c-2f53-4261-8158-c300b7bc7c58" was created successfully 
[HelloWorldTests]  SUCCESS: service "sla-template/dc1e96ee-0f59-4bb5-9864-5be7cc783f3a" created successfully 
[HelloWorldTests]  SUCCESS: service "service/b6a9fd13-b605-4a17-9eb0-d5c25bc50e62" created successfully 
[HelloWorldTests]  FAILED: failed to return list of devices 
[HelloWorldTests]  SUCCESS: service instance null launched successfully 
Devices list returned successfully when test executed manually.
curl -H "Content-Type: …

Changes to landscaper and analytics engine

---

docker-compose-cloud/docker-compose.yml
docker-compose/docker-compose.yml

As discussed in dev call 19.06.2019
This means we don't need a dependency on policies, thus leading to simpler code.
(No issue associated with this PR)

Moved the vpnserver from the fog (agent) to the cloud as discussed

---

docker-compose/docker-compose.yml

New version of analytics engine 0.5.0

---

docker-compose/docker-compose.yml
docker-compose/landscaper.cfg

An updated revision of landscaper container / added 2 new parameters to the landscaper.cfg Fixes #209

An updated revision of landscaper container Fixes #209

---

docker-compose/docker-compose.yml
docs/resource-categorization.md

Updated the docker-compose file with new docker-image of the res-cat module and also added the host information in the docker-compose. Changed and modified the corresponding docs

Updated docker-compose file with new res-cat image 

---

docker-compose/hello-world.sh

This checks that the creation of the agreement was triggered by the Lifecycle Manager.

Check correct creation of agreement on hello world

---

docker-compose/docker-compose.yml

As the topic says, updates #216 as discussed Wedn 17/7/19.

Added vpnclient; updates #216

---

docker-compose/docker-compose.yml
docs/aclib.md
docs/cau_client.md

I have updated the docker-compose.yml file to:
- add section on aclib
- updated cau-client section
Cau-client uses the cloud CAU for the moment.

added calib and upd cau-client images

---

docker-compose/docker-compose.yml
docs/vpnclient.md

Version that doesn't have race with cau-client.
Also switched to using host network; closes jjensenral/vpn#1

vpnclient update

---

docker-compose/docker-compose.yml
docs/landscaper.md

Fixes:
https://github.com/mF2C/landscaper/issues/12 and https://github.com/mF2C/mF2C/issues/223

Landscaper updated to version 0.6.9

---

docker-compose/docker-compose.yml
docs/sla_management.md

This PR also adds the docs.
Output of hello world:
```
$ ./hello-world.sh --include-tests
[CIMITests]      Starting...
[CIMITests]      SUCCESS: cloud-entry-point exists
[CIMITests]      SUCCESS: user authorization working properly
[CIMITests]      SUCCESS: correct 405 on invalid resource collection
[CIMITests]      SUCCESS: correct 404 for non-existent user
[CIMITests]      SUCCESS: user ILnbgPCe created successfully
[CIMITests]      FAILED: no error or wrong error when trying to create ILnbgPCe a second time
parse error: Invalid numeric literal at line 1, column 10
[CIMITests]      FAILED: failed to create new resource
[CIMITests]      SUCCESS: successfully retrieved resource by ID
[CIMITests]      SUCCESS: resource filtering is working
[CIMITests]      FAILED: failed to update resource …
```

Update SLA Management to 0.8.1

---

docker-compose/docker-compose.yml
docker-compose/tests/vpnclient.sh
docs/vpnclient.md

(1) Added integration test for vpnclient; (2) removed CA endpoint from d-c file as discussed Wed 7th (should be safe as cau-client obtains the credential); (3) updated vpnclient docs

Updated vpnclient & added intg test

---

docker-compose/hello-world.sh
docker-compose/tests/aclib.sh
docker-compose/tests/cau-client.sh

Hi could you approve this PR, ta.

Added cau-client and aclib integration tests

---

docker-compose/docker-compose.yml
docs/cimi.md

related to https://github.com/mF2C/cimi/issues/84

upgrade cimi

---

docker-compose/docker-compose.yml
docs/landscaper.md

Landscaper image updated to version 0.6.11

Updated landscaper image, fixes adding and updating container metrics  #172

---

docker-compose/tests/policies.sh

+ Added tests for Identification, Discovery, CAU client and Categorization

policies integration tests v2

---

docker-compose/tests/landscape.sh
docker-compose/tests/recommender.sh
docker-compose/tests/telemetry.sh

Integration tests for Telemetry and Recommender module. 
``
[TelemetryTests]  Starting... 
[TelemetryTests]  SUCCESS: plugins entry exists
[TelemetryTests]  SUCCESS: metrics entry exists
[TelemetryTests]  SUCCESS: task created successfully
``
``
[RecommenderTests]  Starting...
[RecommenderTests]  SUCCESS: optimal triggered successfully
[RecommenderTests]  SUCCESS: analyse triggered successfully
[RecommenderTests]  SUCCESS: optimal for cpu and memory triggered successfully
``

Added telemetry and recommender tests

---

docker-compose/docker-compose.yml
docker-compose/tests/resource-categorization.sh
docs/resource-categorization.md

Added the script for the integration test of resource categorization

Integration test for resource categorization

---

docker-compose/docker-compose.yml
docs/resource-categorization.md

Added the text for `latest-V2.0.20`

---

docker-compose/docker-compose.yml

added health checks for cau-client and aclib

---

docker-compose/docker-compose.yml
docs/landscaper.md

Landscaper updated to version 0.6.13 due to error in generate_files logic.

Landscaper updated to version 0.6.13

---

docker-compose/docker-compose.yml
docs/landscaper.md

- Added wifiAddress field to the device dynamic parser

Landscaper updated to version 0.6.14

---

docker-compose/docker-compose.yml

added the health check functionality for resource-categorization

Healthcheck for resource-categorization

---

docker-compose/docker-compose.yml
docs/vpnclient.md

Healthcheck for vpnclient

---

docker-compose/tests/aclib.sh

add cimi tests

---

docker-compose/docker-compose.yml

Includes initial user and JWT session template bootstrapping.
Linked: mf2c/resource-bootstrap#1, mf2c/resourcemanagement#54.

Update resource bootstrap to v1.3.0.

---

docker-compose/docker-compose.yml

Changed the health check statement for res-cat

Modified the healthecheck statement

---

docker-compose/docker-compose.yml
docs/resource-categorization.md

Added the environment variables field, volume for getting the IP from VPN-client and modified the health check statement for res-cat

Modified the res-cat service in d-c file

---

README.md
docker-compose/install.sh

Solves issue: #262 
- Removed mandatory WiFi iface requirement
* WiFi iface set down on agent shutdown
* Installation will continue even if WiFi is not present
+ Cloud env variable added
* .env file is not overwritten if present in the directory
* Superuser permissions added for required commands
+ New log messages added
* Typos fixed
Tested in the mF2C testbed.

Install.sh update

---

docker-compose/docker-compose.yml
docs/resource-categorization.md

Modified the docker-compose and docs for res-cat version - `latest-V2.0.22`

Updated Docker-Compose with res-cat V2.0.22

---

README.md
docker-compose/docker-compose.yml
docs/sla_management_ui.md

SlaManagement UI is running on port 8000 inside slalite-ui component. Exposed to the outside as :48000.
@cjdcordeiro : please, confirm you agree accessing it through 48000 or suggest other port.
Thanks

Add SlaManagementUI to docker compose

---

docker-compose/tests/landscape.sh

Fixed test for the landscaper, make it not dependent on deployed service

Fixed test for the landscaper, make it not dependent on deployed service #273

---

docker-compose/docker-compose.yml
docs/dcproxy.md
docs/ds1java1.md
docs/logicmodule1.md

New dataclay 2.26 with synchronization in operation id field

---

docker-compose/docker-compose.yml
docs/resource-categorization.md

@cjdcordeiro and @fcarp10  if possible then, please don't remove the branch after merging it with the master branch.

Updated image version

---

docker-compose/docker-compose.yml

Includes initial user force-activation.
Relevant commit: mf2c/resource-bootstrap@ade4400fa5d0c3a2f4d266235b8503f31fcf3130

Update resource bootstrap to v1.4.1.

---

README.md
docs/index.rst
docs/resource-bootstrap.md

Update resource-bootstrap docs up to 1.4.1.

---

README.md
docker-compose/docker-compose.yml
docker-compose/install.sh
docs/policies.md
docs/resource-categorization.md

Code tested and works. However, when I specify the IP of the cloud agent, I'm not able to post the device resource and I get the following error:
```
{
"status": 400,
"message": "type 'device' does not exist"
}
```
I already asked @dgasull about this issue. **When solved, the PR can be accepted.**
Solve issues: https://github.com/mF2C/mF2C/issues/295 and  https://github.com/mF2C/ResourceManagement/issues/58

Policies update

---

agent/docker-compose.yml
agent/docs/resource-categorization.md

Modified the IP collection procedure

Changed res-cat version

---

microagent/mf2c-entrypoint.sh

Updated the ARM version and added the VPN info volume for collecting the device IP

Updated the ARM version for Res-Cat

---

agent/install.sh

* Project directories fixed when install downloaded alone.

install.sh 1.3

---

microagent/mf2c-entrypoint.sh

issue: bad res-cat run command

---

agent/docker-compose.yml
agent/docs/analytics_engine.md

- Added support for multiagent deployment 
- Added Healthcheck
- A downgraded version of numpy as python 2.7 is no longer supported

Upgrade analytics service to version 0.5.7

---

agent/docker-compose.yml
agent/docs/resource-categorization.md

Updated the docs, now @cjdcordeiro I request you to add my new image (`latest-V2.0.28`) from trunk repo to our main repo, then I can modify the d-c file.

Added the docs for new res-cat image

---

agent/docker-compose.yml
agent/docs/policies.md

solves: https://github.com/mF2C/ResourceManagement/issues/77

Policies patch 2.0.12

---

agent/docker-compose.yml
agent/docs/resource-categorization.md
microagent/docker-compose.yml
microagent/mf2c-entrypoint.sh

Before merging this PR into the master, please build a new `microagent` docker image with the following tag - `1.0.4`

Fixed the IP issue for ARM-base and fixed the agentType and Hostname issue

---

agent/tests/der.sh

DER test for an agent was passing in the list of agents to the Lifecycle Manager when deploying a service, now it detects the available agents automatically.

DER test not passing in agents list

---

agent/docker-compose.yml
agent/docs/resource-bootstrap.md

Bootstrap the video analysis service for the microagent.

Upgrade resource-bootstrap to 2.7.3.

---

agent/docker-compose.yml
agent/docs/analytics_engine.md

Added filtering and ordering nodes for required sensors and agent type field described in the service definition.

Upgrade version of analytics engine to 0.6 . Fix for #322

---

agent/docker-compose.yml
agent/docs/gui-dashboard.md

changes in docker-compose to add the GUI Dashboard and LM UI to the agent

GUI Dashboard/LM GUI added to agent

---

agent/docker-compose.yml
agent/docs/resource-categorization.md
microagent/docker-compose.yml
microagent/mf2c-entrypoint.sh

Modified the d-c for agent with new res-cat image and also added the corresponding doc. Also modified the `mf2c-entrypoint.sh` with the new res-cat arm image. 
Solves: https://github.com/mF2C/ResourceManagement/issues/89

Modified the D-C file with new res-cat

---

agent/docker-compose.yml
agent/docs/service_manager.md

SM now adds default values for cpu, disk, memory and network when registering services

updated version of SM

---

agent/docker-compose.yml
agent/docs/policies.md

Policies 2.0.13

---

agent/mf2c.sh

mf2c.sh 1.5

---

agent/docker-compose.yml
agent/docs/resource-bootstrap.md

Opt-in cloud bootstrap, default SLA template.

Upgrade resource-bootstrap to 2.7.5.

---

agent/docker-compose.yml
agent/docs/service_manager.md

Before merging, the docker image has be moved from trunk to the official repository

new version of service manager fixing issues with GUI

---

agent/mf2c.sh

+ sensors and actuators automatically added to the `.env` file from the `setup.json` file.
+ git pull disabled if .git directory is not detected.

mf2c.sh registration fix

---

agent/docker-compose.yml
agent/docs/analytics_engine.md
agent/hello-world.sh

- Fixed agent type and platform affinity. 
- Changed service name passed to optimal in hello world example

Upgraded analytics engine to version 0.61

---

agent/docker-compose.yml
agent/docs/analytics_engine.md

Analytics engine updated to version 0.62:
- Added more robust error handling for Device Dynamics.

Analytics engine updated to version 0.62

---

agent/docker-compose.yml
agent/docs/sla_management.md

Added
* Add availability calculation for COMPSs services
Changed
* Fix service operation reports being ignored

Update SlaManagement version to 0.9.1
